[project]
name = "uv-python-dotenv"
version = "0.1.0"
description = "uv를 가지고 python dotenv를 사용해보는 프로젝트"
readme = "README.md"
requires-python = ">=3.12, <3.14"
dependencies = [
    "python-dotenv>=1.2.1",
    "pandas",
]
